# Tutorial 4
## Numpy and basic Pandas

In [2]:
# Primero se tiene que importar la libreria
import numpy as np

In [3]:
# Primero se crear una lista y luego se convierte a un arreglo de nunpy

price_list = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
price_array = np.array(price_list)
print(price_array, type(price_array))

[143.73 145.83 143.68 144.02 143.5  142.62] <class 'numpy.ndarray'>


In [4]:
# Igualmente se pueden crear arreglos de varias dimensiones 

Ar = np.array([[1,3], [2,4]])
print(Ar, type(Ar))

[[1 3]
 [2 4]] <class 'numpy.ndarray'>


In [5]:
# Se pueden obtener las dimensiones de los arreglos con shape()

print(Ar.shape)

(2, 2)


In [6]:
#Igualmente se puede acceder a los elementos de los arreglos
print(Ar[0])
print(Ar[1])

[1 3]
[2 4]


In [8]:
# y se pueden acceder por las columnas 
print('First column:', Ar[:,0])
print('Second column:', Ar[:,1])

First column: [1 2]
Second column: [3 4]


## Funciones sobre arreglos

In [9]:
# Se aplica la función sobre cada uno de los elementos del arreglo

np.log(price_array)

array([4.96793654, 4.98244156, 4.9675886 , 4.96995218, 4.96633504,
       4.96018375])

In [10]:
# Otra de las funciones puede ser la media
np.mean(price_array)

143.89666666666668

In [11]:
# La desviación estandar
print(np.std(price_array))

0.9673790478515796


In [12]:
# La sumatoria de los elementos del arreglo
print (np.sum(price_array))

863.38


In [13]:
# Obtener el maximo de los elementos del arreglo
print(np.max(price_array))

145.83


## Uso de Pandas

In [14]:
# Primero se importa la libreria 
import pandas as pd

In [15]:
# Primero se convierte una lista de python en una serie de pandas

price = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
s = pd.Series(price)
print (s)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
dtype: float64


In [16]:
# Se le puede agregar indices a la serie, o modificarla 

s = pd.Series(price, index = ['a', 'b', 'c', 'd', 'e', 'f'])
print (s)

a    143.73
b    145.83
c    143.68
d    144.02
e    143.50
f    142.62
dtype: float64


In [17]:
# Se pueden volver a reasignas los indices
s.index = [6,5,4,3,2,1]
print (s)

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64


In [18]:
print(s[1:])
print(s[:-2])


5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64
6    143.73
5    145.83
4    143.68
3    144.02
dtype: float64


In [19]:
# O se pueden reasignar los valores
print(s[4])
s[4] = 0
print (s)

143.68
6    143.73
5    145.83
4      0.00
3    144.02
2    143.50
1    142.62
dtype: float64


In [21]:
# Se pueden asignar el nombre a una serie 

s = pd.Series(price, name = 'Apple Prices')
print (s)
print (s.name)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
Name: Apple Prices, dtype: float64
Apple Prices


In [22]:
# Para obtener la descripción de la serie
print (s.describe())

count      6.000000
mean     143.896667
std        1.059711
min      142.620000
25%      143.545000
50%      143.705000
75%      143.947500
max      145.830000
Name: Apple Prices, dtype: float64


In [23]:
# Se pueden asignar los indices

time_index = pd.date_range('2017-01-01', periods = len(s), freq = 'D')
print(time_index)
s.index = time_index
print (s)

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06'],
              dtype='datetime64[ns]', freq='D')
2017-01-01    143.73
2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
2017-01-06    142.62
Freq: D, Name: Apple Prices, dtype: float64


In [24]:
s.index = [6,5,4,3,2,1]
print (s)
print (s[1])

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
Name: Apple Prices, dtype: float64
142.62


In [25]:
# Se utiliza iloc para acceder a los elementos de las serie
print(s.iloc[1])

145.83


In [26]:
# O tambien se puede acceder al elemento mediante el indice

s.index = time_index
print (s['2017-01-03'])

143.68


In [27]:
# Y se puede acceder a un rando de valores

print (s['2017-01-02':'2017-01-05'])

2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
Freq: D, Name: Apple Prices, dtype: float64


In [28]:
# Se puede acceder a los valores de las series mediante condicionales

print (s[s < np.mean(s)])
print (s[(s > np.mean(s)) & (s < np.mean(s) + 1.64*np.std(s))])

2017-01-01    143.73
2017-01-03    143.68
2017-01-05    143.50
2017-01-06    142.62
Name: Apple Prices, dtype: float64
2017-01-04    144.02
Freq: D, Name: Apple Prices, dtype: float64
